/**
 * Password entropy, crack-time, and quantum-resistance analysis.
 *
 * Pure, dependency-free, and side-effect-free so it can be unit-tested in
 * isolation and reused anywhere (generator advisory, vault health, etc.).
 *
 * ── Crack time ──────────────────────────────────────────────────────────────
 * A brute-force attacker must, on average, try half the keyspace before a hit:
 *   average attempts = 2^(bits - 1)
 *   seconds          = 2^(bits - 1) / guessesPerSecond
 * For strong passwords 2^(bits-1) overflows IEEE-754, so everything is computed
 * in log10 space and only converted back to a Number once it is known to be in
 * a representable range.
 *
 * ── Quantum resistance ──────────────────────────────────────────────────────
 * Grover's algorithm searches an N-element space in ~√N operations, which
 * halves the effective security of a symmetric secret: an n-bit password offers
 * only n/2 bits of security against a quantum adversary. To retain the 128-bit
 * post-quantum security level that AES-256 / CNSA 2.0 / NIST PQC Level 5 target
 * (the baseline this vault is built on), a password therefore needs ≈256 bits
 * of classical entropy. That is the bar for the "Quantum-Proof" badge.
 *
 * References:
 *   - Grover's algorithm halves effective key bits (NIST PQC rationale).
 *   - NIST SP 800-63B: 80+ bits for autogenerated secrets, 100+ for master keys.
 */

/** Seconds in a Julian year (365.25 days). */
const SECONDS_PER_YEAR = 31_557_600;
/** Current age of the universe in years (≈13.8 billion). */
const AGE_OF_UNIVERSE_YEARS = 1.38e10;
const LOG10_2 = Math.log10(2);
const LOG10_YEAR = Math.log10(SECONDS_PER_YEAR);
const LOG10_AGE_UNIVERSE_SECONDS = Math.log10(AGE_OF_UNIVERSE_YEARS) + LOG10_YEAR;

/** Entropy (classical bits) at or above which a password is "Quantum-Proof". */
export const QUANTUM_PROOF_BITS = 256;
/** Entropy at or above which a password is "Quantum-Resistant". */
export const QUANTUM_RESISTANT_BITS = 128;

export type QuantumLevel = 'vulnerable' | 'resistant' | 'proof';

export interface QuantumAssessment {
  /** Classical entropy in bits. */
  bits: number;
  /** Effective bits against a Grover-equipped quantum attacker (bits / 2). */
  postQuantumBits: number;
  level: QuantumLevel;
  /** Convenience flag: true only when level === 'proof'. */
  isQuantumProof: boolean;
}

/**
 * Offline attacker throughput profiles, in guesses per second.
 * Rates reflect attacks against a single fast hash (NTLM/MD5-class):
 *   - online: rate-limited remote login API.
 *   - gpu:    a single modern offline GPU rig.
 *   - nationState: a large offline cluster / well-funded adversary.
 */
export const ATTACKER_PROFILES = {
  online: 1e2,
  gpu: 1e10,
  nationState: 1e12,
} as const;

export type AttackerProfileId = keyof typeof ATTACKER_PROFILES;

export type CrackUnit =
  | 'instant'
  | 'seconds'
  | 'minutes'
  | 'hours'
  | 'days'
  | 'years'
  | 'powerYears';

export interface CrackTime {
  /** log10 of the average seconds to exhaust half the keyspace. */
  log10Seconds: number;
  unit: CrackUnit;
  /**
   * Quantity expressed in `unit`. For 'powerYears' this is the base-10
   * exponent of the number of years (e.g. value 19 → 10^19 years).
   */
  value: number;
  /** True when the time exceeds the current age of the universe. */
  beyondUniverse: boolean;
}

/** Size of the character pool implied by the enabled character classes. */
export function charsetSize(opts: {
  uppercase: boolean;
  lowercase: boolean;
  numbers: boolean;
  symbols: boolean;
}): number {
  let n = 0;
  if (opts.uppercase) n += 26;
  if (opts.lowercase) n += 26;
  if (opts.numbers) n += 10;
  if (opts.symbols) n += 30;
  return n || 1;
}

/** Entropy of a random password of `length` chars drawn from `charset` symbols. */
export function randomPasswordBits(length: number, charset: number): number {
  if (length <= 0 || charset <= 1) return 0;
  return length * Math.log2(charset);
}

/** Entropy of an N-word passphrase drawn from a `wordlistSize`-word list. */
export function passphraseBits(words: number, wordlistSize: number): number {
  if (words <= 0 || wordlistSize <= 1) return 0;
  return words * Math.log2(wordlistSize);
}

/** Classify a password's quantum resistance from its classical entropy. */
export function classifyQuantum(bits: number): QuantumAssessment {
  const safeBits = Number.isFinite(bits) && bits > 0 ? bits : 0;
  let level: QuantumLevel = 'vulnerable';
  if (safeBits >= QUANTUM_PROOF_BITS) level = 'proof';
  else if (safeBits >= QUANTUM_RESISTANT_BITS) level = 'resistant';
  return {
    bits: safeBits,
    postQuantumBits: safeBits / 2,
    level,
    isQuantumProof: level === 'proof',
  };
}

/** Convert a log10-seconds figure into a bucketed, locale-agnostic estimate. */
function bucketFromLog10Seconds(log10Seconds: number): CrackTime {
  const beyondUniverse = log10Seconds > LOG10_AGE_UNIVERSE_SECONDS;

  // Anything under one second is, for our purposes, instant.
  if (!Number.isFinite(log10Seconds) || log10Seconds < 0) {
    return { log10Seconds, unit: 'instant', value: 0, beyondUniverse };
  }

  // Sub-year buckets are small enough to represent as a real Number.
  if (log10Seconds < LOG10_YEAR) {
    const seconds = Math.pow(10, log10Seconds);
    if (seconds < 60) return { log10Seconds, unit: 'seconds', value: Math.max(1, Math.round(seconds)), beyondUniverse };
    if (seconds < 3600) return { log10Seconds, unit: 'minutes', value: Math.round(seconds / 60), beyondUniverse };
    if (seconds < 86_400) return { log10Seconds, unit: 'hours', value: Math.round(seconds / 3600), beyondUniverse };
    return { log10Seconds, unit: 'days', value: Math.round(seconds / 86_400), beyondUniverse };
  }

  const log10Years = log10Seconds - LOG10_YEAR;
  // Number can exactly represent integers up to 2^53 (~9e15); past 10^15 years
  // we switch to an order-of-magnitude representation.
  if (log10Years < 15) {
    return { log10Seconds, unit: 'years', value: Math.pow(10, log10Years), beyondUniverse };
  }
  return { log10Seconds, unit: 'powerYears', value: Math.round(log10Years), beyondUniverse };
}

/**
 * Estimate the average time to brute-force a password of `bits` entropy at a
 * given attacker throughput. Returns a structured, locale-agnostic estimate;
 * the caller is responsible for formatting/translating the units.
 */
export function crackTime(bits: number, guessesPerSecond: number): CrackTime {
  if (!Number.isFinite(bits) || bits <= 0 || guessesPerSecond <= 0) {
    return { log10Seconds: -Infinity, unit: 'instant', value: 0, beyondUniverse: false };
  }
  // log10(2^(bits-1) / rate) = (bits-1)*log10(2) - log10(rate)
  const log10Seconds = (bits - 1) * LOG10_2 - Math.log10(guessesPerSecond);
  return bucketFromLog10Seconds(log10Seconds);
}

/**
 * Crack time against a Grover-equipped quantum attacker. Grover collapses the
 * effective search space to 2^(bits/2), so we evaluate the classical estimator
 * at half the entropy and the same nominal throughput.
 */
export function quantumCrackTime(bits: number, guessesPerSecond: number): CrackTime {
  return crackTime(bits / 2, guessesPerSecond);
}
